e_dfmvclass<-function(explaining=0){

  if(explaining==0) {
  cat("  ", '\n')
  cat("\033[1;32m##  Dataset ---- \033[0m", '\n')
  cat("  #----------------", '\n')
  cat("  arrest", '\n')
  cat("  coffee", '\n')
  cat("  heywood", '\n')
  cat("  OMKthesis", '\n')
  cat("  Path_Ingram", '\n')
  cat("  smartphone2018", '\n')
  cat("  #----------------", '\n')
  cat("  KR_authority", '\n')
  cat("  KR_senior_center", '\n')
  cat("  #----------------", '\n')
  cat("  YS_authority", '\n')
  cat("  YS_commitment", '\n')
  cat("  YS_jobsatisfaction", '\n')
  cat("  YS_jobsatisfaction2", '\n')
  cat("  #----------------", '\n')
  cat("  base", '\n')
  cat("  basic", '\n')
  cat("  con_moderator1", '\n')
  cat("  con_moderator2", '\n')
  cat("  fat", '\n')
  cat("  fat2", '\n')
  cat("  group_moderator", '\n')
  cat("  iris_missing", '\n')
  cat("  lgcm", '\n')
  cat("  matched", '\n')
  cat("  mediation", '\n')
  cat("  mg_sem1", '\n')
  cat("  mg_sem2", '\n')
  cat("  mg_sem2_L", '\n')
  cat("  mroz", '\n')
  cat("  psm_sem", '\n')
  cat("  ", '\n')
  } }
  